[build]
  command = "npm run build"
  publish = "out"
  functions = "out_functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "next"
  targetPort = 3000
  command = "npm run dev"

# Cache images
[[headers]]
  for = "/*.(png|jpg|jpeg|webp|avif|svg|gif)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache videos
[[headers]]
  for = "/*.(mp4|webm)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/*.(woff|woff2|ttf|otf)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"